# Generated by Django 4.1.3 on 2023-12-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gost', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gost28759flangemass',
            options={'verbose_name': 'массы фланцев', 'verbose_name_plural': 'ГОСТ 28759.3-2022 Массы'},
        ),
        migrations.AlterModelOptions(
            name='gost33259typedrawing',
            options={'verbose_name': 'типы', 'verbose_name_plural': 'ГОСТ 33259-2015 чертежи типов фланцев'},
        ),
        migrations.AlterField(
            model_name='gost28759flangevalues',
            name='a1_lower',
            field=models.CharField(blank=True, max_length=6, verbose_name='a1'),
        ),
        migrations.AlterField(
            model_name='gost28759flangevalues',
            name='a_lower',
            field=models.CharField(blank=True, max_length=6, verbose_name='a'),
        ),
        migrations.AlterField(
            model_name='gost28759flangevalues',
            name='b_lower',
            field=models.CharField(blank=True, max_length=6, verbose_name='b'),
        ),
        migrations.AlterField(
            model_name='gost28759flangevalues',
            name='d1',
            field=models.CharField(blank=True, max_length=6, verbose_name='D1'),
        ),
        migrations.AlterField(
            model_name='gost28759flangevalues',
            name='d2',
            field=models.CharField(blank=True, max_length=6, verbose_name='D2'),
        ),
        migrations.AlterField(
            model_name='gost28759flangevalues',
            name='d3',
            field=models.CharField(blank=True, max_length=6, verbose_name='D3'),
        ),
        migrations.AlterField(
            model_name='gost28759flangevalues',
            name='d4',
            field=models.CharField(blank=True, max_length=6, verbose_name='D4'),
        ),
        migrations.AlterField(
            model_name='gost28759flangevalues',
            name='d5',
            field=models.CharField(blank=True, max_length=6, verbose_name='D5'),
        ),
        migrations.AlterField(
            model_name='gost28759flangevalues',
            name='d6',
            field=models.CharField(blank=True, max_length=6, verbose_name='D6'),
        ),
        migrations.AlterField(
            model_name='gost28759flangevalues',
            name='d7',
            field=models.CharField(blank=True, max_length=6, verbose_name='D7'),
        ),
        migrations.AlterField(
            model_name='gost28759flangevalues',
            name='d_lower',
            field=models.CharField(blank=True, max_length=6, verbose_name='d'),
        ),
        migrations.AlterField(
            model_name='gost28759flangevalues',
            name='h',
            field=models.CharField(blank=True, max_length=6, verbose_name='H'),
        ),
        migrations.AlterField(
            model_name='gost28759flangevalues',
            name='s',
            field=models.CharField(blank=True, max_length=6, verbose_name='S0'),
        ),
        migrations.AlterField(
            model_name='gost33259surfacevalues',
            name='b2_lower',
            field=models.CharField(blank=True, max_length=6, verbose_name='b2'),
        ),
        migrations.AlterField(
            model_name='gost33259surfacevalues',
            name='d10',
            field=models.CharField(blank=True, max_length=6, verbose_name='D10'),
        ),
        migrations.AlterField(
            model_name='gost33259surfacevalues',
            name='d11',
            field=models.CharField(blank=True, max_length=6, verbose_name='D11'),
        ),
        migrations.AlterField(
            model_name='gost33259surfacevalues',
            name='d2',
            field=models.CharField(blank=True, max_length=6, verbose_name='D2'),
        ),
        migrations.AlterField(
            model_name='gost33259surfacevalues',
            name='d3_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='D3'),
        ),
        migrations.AlterField(
            model_name='gost33259surfacevalues',
            name='d3_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='D3'),
        ),
        migrations.AlterField(
            model_name='gost33259surfacevalues',
            name='d4_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='D4'),
        ),
        migrations.AlterField(
            model_name='gost33259surfacevalues',
            name='d4_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='D4'),
        ),
        migrations.AlterField(
            model_name='gost33259surfacevalues',
            name='d5_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='D5'),
        ),
        migrations.AlterField(
            model_name='gost33259surfacevalues',
            name='d5_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='D5'),
        ),
        migrations.AlterField(
            model_name='gost33259surfacevalues',
            name='d6_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='D6'),
        ),
        migrations.AlterField(
            model_name='gost33259surfacevalues',
            name='d6_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='D6'),
        ),
        migrations.AlterField(
            model_name='gost33259surfacevalues',
            name='d7',
            field=models.CharField(blank=True, max_length=6, verbose_name='D7'),
        ),
        migrations.AlterField(
            model_name='gost33259surfacevalues',
            name='d8',
            field=models.CharField(blank=True, max_length=6, verbose_name='D8'),
        ),
        migrations.AlterField(
            model_name='gost33259surfacevalues',
            name='d9',
            field=models.CharField(blank=True, max_length=6, verbose_name='D9'),
        ),
        migrations.AlterField(
            model_name='gost33259surfacevalues',
            name='h1_lower',
            field=models.CharField(blank=True, max_length=6, verbose_name='h1'),
        ),
        migrations.AlterField(
            model_name='gost33259surfacevalues',
            name='h2_lower',
            field=models.CharField(blank=True, max_length=6, verbose_name='h2'),
        ),
        migrations.AlterField(
            model_name='gost33259surfacevalues',
            name='h3_lower',
            field=models.CharField(blank=True, max_length=6, verbose_name='h3'),
        ),
        migrations.AlterField(
            model_name='gost33259surfacevalues',
            name='h4_lower',
            field=models.CharField(blank=True, max_length=6, verbose_name='h4'),
        ),
        migrations.AlterField(
            model_name='gost33259surfacevalues',
            name='h5_lower',
            field=models.CharField(blank=True, max_length=6, verbose_name='h5'),
        ),
        migrations.AlterField(
            model_name='gost33259surfacevalues',
            name='h_lower',
            field=models.CharField(blank=True, max_length=6, verbose_name='h'),
        ),
        migrations.AlterField(
            model_name='gost33259type01',
            name='b_lower_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='b'),
        ),
        migrations.AlterField(
            model_name='gost33259type01',
            name='b_lower_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='b'),
        ),
        migrations.AlterField(
            model_name='gost33259type01',
            name='c1_lower',
            field=models.CharField(blank=True, max_length=6, verbose_name='c1'),
        ),
        migrations.AlterField(
            model_name='gost33259type01',
            name='d1',
            field=models.CharField(blank=True, max_length=6, verbose_name='D1'),
        ),
        migrations.AlterField(
            model_name='gost33259type01',
            name='d_lower_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='d'),
        ),
        migrations.AlterField(
            model_name='gost33259type01',
            name='d_lower_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='d'),
        ),
        migrations.AlterField(
            model_name='gost33259type01',
            name='d_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='D'),
        ),
        migrations.AlterField(
            model_name='gost33259type01',
            name='d_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='D'),
        ),
        migrations.AlterField(
            model_name='gost33259type01',
            name='dv_lower_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='dв'),
        ),
        migrations.AlterField(
            model_name='gost33259type01',
            name='dv_lower_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='dв'),
        ),
        migrations.AlterField(
            model_name='gost33259type01',
            name='n_lower_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='n'),
        ),
        migrations.AlterField(
            model_name='gost33259type01',
            name='n_lower_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='n'),
        ),
        migrations.AlterField(
            model_name='gost33259type01',
            name='pin_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='Диаметр шпилек'),
        ),
        migrations.AlterField(
            model_name='gost33259type01',
            name='pin_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='Диаметр шпилек'),
        ),
        migrations.AlterField(
            model_name='gost33259type02',
            name='b1_lower_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='b1'),
        ),
        migrations.AlterField(
            model_name='gost33259type02',
            name='b1_lower_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='b1'),
        ),
        migrations.AlterField(
            model_name='gost33259type02',
            name='b_lower_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='b'),
        ),
        migrations.AlterField(
            model_name='gost33259type02',
            name='b_lower_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='b'),
        ),
        migrations.AlterField(
            model_name='gost33259type02',
            name='c1_lower',
            field=models.CharField(blank=True, max_length=6, verbose_name='c1'),
        ),
        migrations.AlterField(
            model_name='gost33259type02',
            name='c_lower_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='c'),
        ),
        migrations.AlterField(
            model_name='gost33259type02',
            name='c_lower_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='c'),
        ),
        migrations.AlterField(
            model_name='gost33259type02',
            name='d0_row_one',
            field=models.CharField(blank=True, max_length=15, verbose_name='D0'),
        ),
        migrations.AlterField(
            model_name='gost33259type02',
            name='d0_row_two',
            field=models.CharField(blank=True, max_length=15, verbose_name='D0'),
        ),
        migrations.AlterField(
            model_name='gost33259type02',
            name='d1',
            field=models.CharField(blank=True, max_length=6, verbose_name='D1'),
        ),
        migrations.AlterField(
            model_name='gost33259type02',
            name='d2',
            field=models.CharField(blank=True, max_length=6, verbose_name='D2'),
        ),
        migrations.AlterField(
            model_name='gost33259type02',
            name='d_lower_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='d'),
        ),
        migrations.AlterField(
            model_name='gost33259type02',
            name='d_lower_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='d'),
        ),
        migrations.AlterField(
            model_name='gost33259type02',
            name='d_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='D'),
        ),
        migrations.AlterField(
            model_name='gost33259type02',
            name='d_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='D'),
        ),
        migrations.AlterField(
            model_name='gost33259type02',
            name='dv_lower_row_one',
            field=models.CharField(blank=True, max_length=15, verbose_name='dв'),
        ),
        migrations.AlterField(
            model_name='gost33259type02',
            name='dv_lower_row_two',
            field=models.CharField(blank=True, max_length=15, verbose_name='dв'),
        ),
        migrations.AlterField(
            model_name='gost33259type02',
            name='n_lower_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='n'),
        ),
        migrations.AlterField(
            model_name='gost33259type02',
            name='n_lower_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='n'),
        ),
        migrations.AlterField(
            model_name='gost33259type02',
            name='pin_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='Диаметр шпилек'),
        ),
        migrations.AlterField(
            model_name='gost33259type02',
            name='pin_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='Диаметр шпилек'),
        ),
        migrations.AlterField(
            model_name='gost33259type11',
            name='b_lower_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='b'),
        ),
        migrations.AlterField(
            model_name='gost33259type11',
            name='b_lower_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='b'),
        ),
        migrations.AlterField(
            model_name='gost33259type11',
            name='d1',
            field=models.CharField(blank=True, max_length=6, verbose_name='D1'),
        ),
        migrations.AlterField(
            model_name='gost33259type11',
            name='d1_lower_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='d1'),
        ),
        migrations.AlterField(
            model_name='gost33259type11',
            name='d1_lower_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='d1'),
        ),
        migrations.AlterField(
            model_name='gost33259type11',
            name='d_lower_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='d'),
        ),
        migrations.AlterField(
            model_name='gost33259type11',
            name='d_lower_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='d'),
        ),
        migrations.AlterField(
            model_name='gost33259type11',
            name='d_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='D'),
        ),
        migrations.AlterField(
            model_name='gost33259type11',
            name='d_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='D'),
        ),
        migrations.AlterField(
            model_name='gost33259type11',
            name='dm_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='Dm'),
        ),
        migrations.AlterField(
            model_name='gost33259type11',
            name='dm_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='Dm'),
        ),
        migrations.AlterField(
            model_name='gost33259type11',
            name='dn_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='Dn'),
        ),
        migrations.AlterField(
            model_name='gost33259type11',
            name='dn_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='Dn'),
        ),
        migrations.AlterField(
            model_name='gost33259type11',
            name='h1',
            field=models.CharField(blank=True, max_length=6, verbose_name='H1'),
        ),
        migrations.AlterField(
            model_name='gost33259type11',
            name='h_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='H'),
        ),
        migrations.AlterField(
            model_name='gost33259type11',
            name='h_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='H'),
        ),
        migrations.AlterField(
            model_name='gost33259type11',
            name='n_lower_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='n'),
        ),
        migrations.AlterField(
            model_name='gost33259type11',
            name='n_lower_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='n'),
        ),
        migrations.AlterField(
            model_name='gost33259type11',
            name='pin_row_one',
            field=models.CharField(blank=True, max_length=6, verbose_name='Диаметр шпилек'),
        ),
        migrations.AlterField(
            model_name='gost33259type11',
            name='pin_row_two',
            field=models.CharField(blank=True, max_length=6, verbose_name='Диаметр шпилек'),
        ),
    ]
