# Generated by Django 4.1.3 on 2023-05-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeamGost26020TypeB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Номер швеллера')),
                ('height', models.FloatField(verbose_name='h')),
                ('width', models.FloatField(verbose_name='b')),
                ('thickness', models.FloatField(verbose_name='s')),
                ('thickness_t', models.FloatField(verbose_name='t')),
                ('weight', models.FloatField(verbose_name='Масса, 1м/кг')),
            ],
            options={
                'verbose_name': 'двутавры тип "Б" по ГОСТ 26020-83',
                'verbose_name_plural': 'Двутавры ГОСТ 26020-83 тип "Б"',
            },
        ),
        migrations.CreateModel(
            name='BeamGost26020TypeD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Номер швеллера')),
                ('height', models.FloatField(verbose_name='h')),
                ('width', models.FloatField(verbose_name='b')),
                ('thickness', models.FloatField(verbose_name='s')),
                ('thickness_t', models.FloatField(verbose_name='t')),
                ('weight', models.FloatField(verbose_name='Масса, 1м/кг')),
            ],
            options={
                'verbose_name': 'двутавры тип "Д" по ГОСТ 26020-83',
                'verbose_name_plural': 'Двутавры ГОСТ 26020-83 тип "Д"',
            },
        ),
        migrations.CreateModel(
            name='BeamGost26020TypeK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Номер швеллера')),
                ('height', models.FloatField(verbose_name='h')),
                ('width', models.FloatField(verbose_name='b')),
                ('thickness', models.FloatField(verbose_name='s')),
                ('thickness_t', models.FloatField(verbose_name='t')),
                ('weight', models.FloatField(verbose_name='Масса, 1м/кг')),
            ],
            options={
                'verbose_name': 'двутавры тип "К" по ГОСТ 26020-83',
                'verbose_name_plural': 'Двутавры ГОСТ 26020-83 тип "К"',
            },
        ),
        migrations.CreateModel(
            name='BeamGost26020TypeS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Номер швеллера')),
                ('height', models.FloatField(verbose_name='h')),
                ('width', models.FloatField(verbose_name='b')),
                ('thickness', models.FloatField(verbose_name='s')),
                ('thickness_t', models.FloatField(verbose_name='t')),
                ('weight', models.FloatField(verbose_name='Масса, 1м/кг')),
            ],
            options={
                'verbose_name': 'двутавры тип "С" по ГОСТ 26020-83',
                'verbose_name_plural': 'Двутавры ГОСТ 26020-83 тип "С"',
            },
        ),
        migrations.CreateModel(
            name='BeamGost26020TypeSh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Номер швеллера')),
                ('height', models.FloatField(verbose_name='h')),
                ('width', models.FloatField(verbose_name='b')),
                ('thickness', models.FloatField(verbose_name='s')),
                ('thickness_t', models.FloatField(verbose_name='t')),
                ('weight', models.FloatField(verbose_name='Масса, 1м/кг')),
            ],
            options={
                'verbose_name': 'двутавры тип "Ш" по ГОСТ 26020-83',
                'verbose_name_plural': 'Двутавры ГОСТ 26020-83 тип "Ш"',
            },
        ),
        migrations.CreateModel(
            name='BeamGost8239',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Номер швеллера')),
                ('height', models.FloatField(verbose_name='h')),
                ('width', models.FloatField(verbose_name='b')),
                ('thickness', models.FloatField(verbose_name='s')),
                ('thickness_t', models.FloatField(verbose_name='t')),
                ('weight', models.FloatField(verbose_name='Масса, 1м/кг')),
            ],
            options={
                'verbose_name': 'двутавры по ГОСТ 8239-89',
                'verbose_name_plural': 'Двутавры ГОСТ 8239-89',
            },
        ),
        migrations.CreateModel(
            name='ChannelTypeC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Номер швеллера')),
                ('height', models.FloatField(verbose_name='h')),
                ('width', models.FloatField(verbose_name='b')),
                ('thickness', models.FloatField(verbose_name='s')),
                ('thickness_t', models.FloatField(verbose_name='t')),
                ('weight', models.FloatField(verbose_name='Масса, 1м/кг')),
            ],
            options={
                'verbose_name': 'швеллеры серии "С"',
                'verbose_name_plural': 'Швеллер "С" ГОСТ8240-97',
            },
        ),
        migrations.CreateModel(
            name='ChannelTypeE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Номер швеллера')),
                ('height', models.FloatField(verbose_name='h')),
                ('width', models.FloatField(verbose_name='b')),
                ('thickness', models.FloatField(verbose_name='s')),
                ('thickness_t', models.FloatField(verbose_name='t')),
                ('weight', models.FloatField(verbose_name='Масса, 1м/кг')),
            ],
            options={
                'verbose_name': 'швеллеры серии "Э"',
                'verbose_name_plural': 'Швеллер "Э" ГОСТ 8240-97',
            },
        ),
        migrations.CreateModel(
            name='ChannelTypeL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Номер швеллера')),
                ('height', models.FloatField(verbose_name='h')),
                ('width', models.FloatField(verbose_name='b')),
                ('thickness', models.FloatField(verbose_name='s')),
                ('thickness_t', models.FloatField(verbose_name='t')),
                ('weight', models.FloatField(verbose_name='Масса, 1м/кг')),
            ],
            options={
                'verbose_name': 'швеллеры серии "Л"',
                'verbose_name_plural': 'Швеллер "Л" ГОСТ8240-97',
            },
        ),
        migrations.CreateModel(
            name='ChannelTypeP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Номер швеллера')),
                ('height', models.FloatField(verbose_name='h')),
                ('width', models.FloatField(verbose_name='b')),
                ('thickness', models.FloatField(verbose_name='s')),
                ('thickness_t', models.FloatField(verbose_name='t')),
                ('weight', models.FloatField(verbose_name='Масса, 1м/кг')),
            ],
            options={
                'verbose_name': 'швеллеры серии "П"',
                'verbose_name_plural': 'Швеллер "П" ГОСТ 8240-97',
            },
        ),
        migrations.CreateModel(
            name='ChannelTypeY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Номер швеллера')),
                ('height', models.FloatField(verbose_name='h')),
                ('width', models.FloatField(verbose_name='b')),
                ('thickness', models.FloatField(verbose_name='s')),
                ('thickness_t', models.FloatField(verbose_name='t')),
                ('weight', models.FloatField(verbose_name='Масса, 1м/кг')),
            ],
            options={
                'verbose_name': 'швеллеры серии "У"',
                'verbose_name_plural': 'Швеллер "У" ГОСТ 8240-97',
            },
        ),
        migrations.CreateModel(
            name='CornerEqualShelvesGost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Размер')),
                ('side', models.FloatField(verbose_name='Сторона уголка, a')),
                ('thickness', models.FloatField(verbose_name='Толщина, t')),
                ('weight', models.FloatField(verbose_name='Масса, 1м/кг')),
            ],
        ),
    ]
