# Generated by Django 4.1.3 on 2023-05-18 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название штуцера')),
                ('purpose', models.CharField(max_length=60, verbose_name='Назначение штуцера')),
                ('dn_passage', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Условный проход')),
                ('pn', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Давление номинальное')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование металла')),
                ('density', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Плотность металла (кг/м3)')),
            ],
        ),
        migrations.CreateModel(
            name='NameCapacitiveEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_equipment', models.CharField(max_length=60, verbose_name='Наименование аппарата')),
                ('calc_number', models.CharField(max_length=30, unique=True, verbose_name='Наряд-заказ №')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор обсчета')),
            ],
            options={
                'verbose_name': 'обсчеты',
                'verbose_name_plural': 'Обсчет (наименование)',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='TypeEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='горизонтальный/вертикальный', max_length=30, verbose_name='Тип аппарата')),
            ],
            options={
                'verbose_name': 'тип емкостного аппарата',
                'verbose_name_plural': 'Тип оборудования',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_capacitive_device', models.CharField(choices=[('ОСТ 26-2091-93', 'Горизонтальные ОСТ 26-2091-93'), ('АТК 24.200.03-90', 'Вертикальные АТК 24.200.03-90')], max_length=40, verbose_name='Тип опор')),
                ('support_capacitive_device_quantity', models.IntegerField(verbose_name='Количество опор')),
                ('thermal_insulation', models.CharField(max_length=200, verbose_name='Наличие теплоизоляции')),
                ('thermal_insulation_quantity', models.IntegerField(verbose_name='Количество крепления для теплоизоляции')),
                ('thermal_insulation_type', models.CharField(choices=[('С2', 'Скоба С2'), ('В1', 'Втулка В1')], max_length=10, verbose_name='Тип крепления для теплоизоляции')),
                ('overlays_service_platform', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, verbose_name='Накладки для площадки')),
                ('ladder', models.CharField(choices=[('Нет', 'Нет'), ('Да, 1 шт.', 'Да, 1 шт.'), ('Да, 2 шт.', 'Да, 2 шт.')], max_length=10, verbose_name='Лестница внутри аппарата')),
                ('hydrogen_sulfide', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=5, verbose_name='Содержание сероводорода')),
                ('hydrogen_sulfide_group', models.CharField(blank=True, max_length=5, null=True, verbose_name='Группа по ГОСТ 34233.1-2017')),
                ('corrosion', models.IntegerField(verbose_name='Коррозия, мм')),
                ('service_life', models.IntegerField(verbose_name='Срок службы, лет')),
                ('heat_treatment', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=5, verbose_name='Термообработка')),
                ('working_temperature', models.CharField(max_length=40, verbose_name='Температура рабочая')),
                ('calculated_temperature', models.CharField(max_length=10, verbose_name='Температура расчетная')),
                ('design_pressure', models.CharField(max_length=10, verbose_name='Расчетное давление')),
                ('density', models.CharField(max_length=50, verbose_name='Плотность рабочей среды')),
                ('steaming_temperature', models.CharField(max_length=100, verbose_name='Температура пропарки')),
                ('seismic_activity', models.CharField(max_length=5, verbose_name='Сейсмичность, баллов')),
                ('coating_external', models.CharField(max_length=200, verbose_name='Наружное покрытие')),
                ('coating_internal', models.CharField(max_length=200, verbose_name='Внутренне покрытие')),
                ('conservation_requirement', models.CharField(max_length=150, verbose_name='Требование консервации')),
                ('visual_identification', models.CharField(max_length=200, verbose_name='Требования к визуальной идентификации')),
                ('spare_parts', models.CharField(max_length=200, verbose_name='ЗИП')),
                ('departures_fittings', models.CharField(max_length=250, verbose_name='Вылеты штуцеров')),
                ('flange_coils', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=5, verbose_name='Наличие фланцевых катушек')),
                ('rotary_fl_stoppers', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=5, verbose_name='Наличие поворотных заглушек')),
                ('calculation_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='capacitive_equipment.namecapacitiveequipment')),
            ],
            options={
                'verbose_name': 'параметры обсчета',
                'verbose_name_plural': 'Параметры обсчета',
            },
        ),
        migrations.CreateModel(
            name='OtherProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Наименование изделия')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Масса')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Количество')),
                ('calculation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitive_equipment.namecapacitiveequipment')),
            ],
        ),
        migrations.AddField(
            model_name='namecapacitiveequipment',
            name='type_equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='capacitive_equipment.typeequipment', verbose_name='Тип аппарата'),
        ),
        migrations.CreateModel(
            name='CaseDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Диаметр')),
                ('thickness', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Толщина')),
                ('length', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Длинна')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Количество')),
                ('calculation_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitive_equipment.namecapacitiveequipment')),
                ('material', models.ForeignKey(default='не указан', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='capacitive_equipment.material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bushing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Диаметр')),
                ('thickness', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Толщина')),
                ('length', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Длинна')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Количество')),
                ('calculation_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitive_equipment.namecapacitiveequipment')),
                ('material', models.ForeignKey(default='не указан', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='capacitive_equipment.material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BranchPipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Диаметр')),
                ('thickness', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Толщина')),
                ('length', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Длинна')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Количество')),
                ('calculation_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitive_equipment.namecapacitiveequipment')),
                ('material', models.ForeignKey(default='не указан', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='capacitive_equipment.material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bottoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitive_equipment.namecapacitiveequipment')),
            ],
        ),
    ]
